# ----
# Site

title: Equipe
description: API documentation for Equipe https://app.equipe.com
url: http://api-docs.equipe.com
google_analytics_key:
permalink: pretty

collections:
  documentation:
    title: Documentation
    position: 1
  federation_api:
    title: Federation APIs
    position: 2
  models:
    title: Federation Models
    position: 3
  api:
    title: APIs
    position: 4
  more:
    title: More
    position: 5

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
